#Main installation actions
#https://clickhouse.yandex/docs/en/getting_started/index.html#installation

- name: Install by YUM | Ensure clickhouse repo GPG key imported
  rpm_key:
    state: present
    key: "{{ clickhouse_repo_key }}"
  tags: [install]
  become: true

- name: Install by YUM | Ensure clickhouse repo installed
  yum_repository:
    name: clickhouse
    file: clickhouse
    description: "Clickhouse repo"
    baseurl: "{{ clickhouse_repo }}"
    enabled: yes
    gpgcheck: 1
    gpgkey: "{{ clickhouse_repo_key }}"
  tags: [install]
  become: true

- name: Install by YUM | Ensure clickhouse package installed (latest)
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ clickhouse_package }}"
  become: true
  tags: [install]
  when: clickhouse_version == "*"

- name: Install by YUM | Ensure clickhouse package installed (version {{ clickhouse_version }})
  yum:
    name: "{{ item }}-{{ clickhouse_version }}"
    state: present
    disable_gpg_check: yes # Because Package clickhouse-server-base-19.4.0-2.x86_64.rpm is not signed
  with_items: "{{ clickhouse_package }}"
  become: true
  tags: [install]
  when: clickhouse_version != "*"

- name: Install by YUM | Ensure clickhouse enabled and started by Systemd
  systemd:
    name: clickhouse-server
    state: started
    enabled: yes
    daemon_reload: yes
  tags: [install]
  become: yes
  when: ansible_service_mgr == 'systemd'

- name: Install by YUM | Ensure clickhouse enabled and started by generic service
  service:
    name: clickhouse-server
    state: started
    enabled: yes
  tags: [install]
  become: yes
  when: ansible_service_mgr != 'systemd'