#Main installation actions
#https://clickhouse.yandex/docs/en/getting_started/index.html#installation

- name: Uninstall by YUM | Ensure clickhouse package uninstalled
  yum:
    name: "{{ item }}-{{ clickhouse_version }}"
    state: absent
    autoremove: yes
  with_items: "{{ clickhouse_package }}"
  become: true

- name: Uninstall by YUM | Ensure clickhouse repo uninstalled
  yum_repository:
    name: clickhouse
    file: clickhouse
    state: absent
  become: true

- name: Uninstall by YUM | Ensure clickhouse key uninstalled
  rpm_key:
    key: "{{ clickhouse_repo_key }}"
    state: absent
  become: true

- name: Remove clickhouse config,data and logs
  file:
    dest: "{{ item }}"
    state: absent
  with_items:
    - "{{ clickhouse_path_logdir }}"
    - "{{ clickhouse_path_configdir }}"
    - "{{ clickhouse_path_tmp }}"
    - "{{ clickhouse_path_data }}"
  become: true
  when: clickhouse_remove_full|bool == True
