#Main installation actions
#https://clickhouse.yandex/docs/en/getting_started/index.html#installation

- name: Uninstall by YUM | Package uninstallation
  yum:
    name: "{{ item }}"
    state: absent
  with_items: "{{ clickhouse_package }}"
  become: true

- name: Uninstall by YUM | Remove repository
  yum_repository:
    name: altinity_clickhouse
    state: absent
  become: true

- name: Uninstall by YUM | Remove clickhouse config,data and logs
  file:
    dest: "{{ item }}"
    state: absent
  with_items:
    - "{{ clickhouse_path_logdir }}"
    - "{{ clickhouse_path_configdir }}"
    - "{{ clickhouse_path_tmp }}"
    - "{{ clickhouse_path_data }}"
  become: true
  when: clickhouse_remove_full|bool == True
